= Google Test
:toc: preamble

image:https://travis-ci.org/google/googletest.svg?branch=master[Build Status,link=https://travis-ci.org/google/googletest]
image:https://ci.appveyor.com/api/projects/status/4o38plt0xbo1ubc8/branch/master?svg=true[Build status,link=https://ci.appveyor.com/project/GoogleTestAppVeyor/googletest/branch/master]

== Foreword

*Future Plans*:
* 1.8.x Release - https://github.com/google/googletest/releases/tag/release-1.8.1[the 1.8.x] is the last release that works with pre-C++11 compilers. The 1.8.x will not accept any requests for any new features and any bugfix requests will only be accepted if proven "critical"
* Post 1.8.x - work to improve/cleanup/pay technical debt. When this work is completed there will be a 1.9.x tagged release
* Post 1.9.x googletest will follow https://abseil.io/about/philosophy[Abseil Live at Head philosophy]

Welcome to *Google Test*, Google's C++ test framework!

This repository is a merger of the formerly separate GoogleTest and
GoogleMock projects. These were so closely related that it makes sense to
maintain and release them together.

Please see the mailing list at googletestframework@googlegroups.com for questions, discussions, and development.
There is also an IRC channel on https://webchat.oftc.net/[OFTC] (irc.oftc.net) #gtest available.

Getting started information for *Google Test* is available in the
link:googletest/docs/primer.adoc[Google Test Primer] documentation.

*Google Mock* is an extension to Google Test for writing and using C++ mock
classes. See the separate link:googlemock/README.adoc[Google Mock documentation].

More detailed documentation for googletest (including build instructions) are
in its interior link:googletest/README.adoc[googletest/README.adoc] file.

== Features

* An https://en.wikipedia.org/wiki/XUnit[xUnit] test framework.
* Test discovery.
* A rich set of assertions.
* User-defined assertions.
* Death tests.
* Fatal and non-fatal failures.
* Value-parameterized tests.
* Type-parameterized tests.
* Various options for running the tests.
* XML test report generation.

== Platforms

Google test has been used on a variety of platforms:

* Linux
* Mac OS X
* Windows
* Cygwin
* MinGW
* Windows Mobile
* Symbian

== Who Is Using Google Test?

In addition to many internal projects at Google, Google Test is also used by
the following notable projects:

* The http://www.chromium.org/[Chromium projects] (behind the Chrome
browser and Chrome OS).
* The http://llvm.org/[LLVM] compiler.
* https://github.com/google/protobuf[Protocol Buffers], Google's data
interchange format.
* The http://opencv.org/[OpenCV] computer vision library.
* https://github.com/tiny-dnn/tiny-dnn[tiny-dnn]: header only, dependency-free deep learning framework in C++11.

== Related Open Source Projects

https://github.com/nholthaus/gtest-runner[GTest Runner] is a Qt5 based automated test-runner and Graphical User Interface with powerful features for Windows and Linux platforms.

https://github.com/ospector/gtest-gbar[Google Test UI] is test runner that runs
your test binary, allows you to track its progress via a progress bar, and
displays a list of test failures. Clicking on one shows failure text. Google
Test UI is written in C#.

https://github.com/kinow/gtest-tap-listener[GTest TAP Listener] is an event
listener for Google Test that implements the
https://en.wikipedia.org/wiki/Test_Anything_Protocol[TAP protocol] for test
result output. If your test runner understands TAP, you may find it useful.

https://github.com/google/gtest-parallel[gtest-parallel] is a test runner that
runs tests from your binary in parallel to provide significant speed-up.

https://marketplace.visualstudio.com/items?itemName=DavidSchuldenfrei.gtest-adapter[GoogleTest Adapter] is a VS Code extension allowing to view Google Tests in a tree view, and run/debug your tests.

== Requirements

Google Test is designed to have fairly minimal requirements to build
and use with your projects, but there are some. Currently, we support
Linux, Windows, Mac OS X, and Cygwin. We will also make our best
effort to support other platforms (e.g. Solaris, AIX, and z/OS).
However, since core members of the Google Test project have no access
to these platforms, Google Test may have outstanding issues there. If
you notice any problems on your platform, please notify
https://groups.google.com/forum/#!forum/googletestframework[googletestframework@googlegroups.com]. Patches for fixing them are
even more welcome!

=== Linux Requirements

These are the base requirements to build and use Google Test from a source
package (as described below):

* GNU-compatible Make or gmake
* POSIX-standard shell
* POSIX(-2) Regular Expressions (regex.h)
* A C++11-standard-compliant compiler

=== Windows Requirements

* Microsoft Visual C++ 2015 or newer

=== Cygwin Requirements

* Cygwin v1.5.25-14 or newer

=== Mac OS X Requirements

* Mac OS X v10.4 Tiger or newer
* Xcode Developer Tools

== Contributing change

Please read the link:CONTRIBUTING.adoc[`CONTRIBUTING.adoc`] for details on
how to contribute to this project.

Happy testing!
