LIBNAME=${PRODUCT_NAME}
GMOCK_LIBRARY_DIR_PATH=`pwd`/../lib
echo "GMOCK_LIBRARY_DIR_PATH = ${GMOCK_LIBRARY_DIR_PATH}"
cd "${CONFIGURATION_BUILD_DIR}"
ln -fs "${GMOCK_LIBRARY_DIR_PATH}/lib${LIBNAME}.a" "lib${LIBNAME}.a"

cd "${TARGET_BUILD_DIR}"
ln -fs "${GMOCK_LIBRARY_DIR_PATH}/lib${LIBNAME}.a" "lib${LIBNAME}.a"
